version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - '3000:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  yak-api:
    build: .
    env_file:
      - ./.env
    depends_on:
      - yak-mongo

  yak-mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
