version: '3'
services:
  nginx:
    ports:
      - '3000:80'

  yak-api:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev