version: '3'
services:
  nginx:
    ports:
      - '3000:80'

  yak-api:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  yak-mongo:
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=yak
      - MONGO_INITDB_ROOT_PASSWORD=Yukino@2022!
