version: '3'
services:
  nginx:
    ports:
      - '80:80'

  yak-api:
    deploy:
      replicas: 8
      restart_policy:
        condition: any
      update_policy:
        parallelism: 2
        delay: 15s
        failure_action: rollback
    build:
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    command: npm build/index.js
