version: '3'
services:
  nginx:
    ports:
      - '80:80'

  yak-api:
    build:
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    command: npm build/index.js